// contacts.ts

export const team = [
  {
    sno: 1,
    name: 'Sayantan Roy',
    position: '',
    founder: 'yes',
    email: 'arko@dubotech.com',
    linkedin: 'https://www.linkedin.com/in/sayantan-roy-arko/',
    image: 'assets/team/arko.jpg',
  },
  {
    sno: 1,
    name: 'NAYEM HOSSAIN SAIKAT',
    position: '',
    founder: 'yes',
    email: 'nhsaikat@dubotech.com',
    linkedin: 'https://www.linkedin.com/in/saikat20/',
    image: 'assets/team/saikat.jpg',
  },
  {
    sno: 1,
    name: 'A.T.M. Masum Billah (Mishu)',
    position: '',
    founder: 'yes',
    email: 'masumbillah@dubotech.com',
    linkedin: 'https://www.linkedin.com/in/masum-billah-mishu/',
    image: 'assets/team/mishu.jpg',
  },
  {
    sno: 1,
    name: 'Md Mahfujul Haque',
    position: '',
    founder: 'yes',
    email: 'md.mahfujul.haque@dubotech.com',
    linkedin: 'Md. Mahfujul Haque',
    image: 'assets/team/mahfujul.jpg',
  },
  {
    sno: 1,
    name: 'Soumik Hasan Shranto ',
    position: '',
    founder: 'yes',
    email: 'shasan.shrantro@dubotech.com',
    linkedin: 'https://www.linkedin.com/in/hasanshranto/',
    image: 'assets/team/shranto.jpg',
  },
  {
    sno: 1,
    name: 'Z.K. Xenon',
    position: '',
    founder: 'yes',
    email: '',
    linkedin: 'https://www.linkedin.com/in/zkwaitforitxenon/',
    image: 'assets/team/xenon.jpg',
  },
  {
    sno: 1,
    name: 'Person 6',
    position: '',
    founder: 'no',
    email: '',
    linkedin: '',
    image: 'assets/team/1.png',
  },
  {
    sno: 1,
    name: 'Person 7',
    position: '',
    founder: 'no',
    email: '',
    linkedin: '',
    image: 'assets/team/1.png',
  },
  {
    sno: 1,
    name: 'Person 8',
    position: '',
    founder: 'no',
    email: '',
    linkedin: '',
    image: 'assets/team/1.png',
  },
  {
    sno: 1,
    name: 'Person 9',
    position: '',
    founder: 'no',
    email: '',
    linkedin: '',
    image: 'assets/team/1.png',
  },
];
